# WP2: Chemical pollution

## Background

> Chemical pollution represents a leading threat to human health, wildlife, and ecosystems around the world (Landrigan et al. 2018). In fact, increases in the diversity and volume of novel synthetic chemicals released into the environment now far outpace other key drivers of global change (e.g. rising atmospheric CO2, habitat loss; Bernhardt et al. 2017). This trend is the result of rapidly increasing chemical use, with the global chemicals industry—currently valued at >US$5 trillion—projected to double in size between 2017 and 2030 (UNEP 2019). The spread of novel environmental contaminants is concerning given that many ecosystems are already inundated with myriad organic and inorganic chemicals released by human activities, including metals, pesticides, pharmaceuticals, and per- and polyfluoroalkyl substances (PFAS). Moreover, chemical pollution continues to accelerate large-scale wildlife losses, including dramatic declines in the abundance and biodiversity of insects (Sánchez‐Bayo and Wyckhuys 2019), avifauna (Rosenberg et al. 2019), and aquatic species (Tickner et al. 2020). A much less studied, but very important, aspect of chemical pollution is the increased vulnerability to pathogens and parasites that exposed wildlife, like fish, experience. This reduction in immunocompetence, combined with the reduced energy available to invest in life sustaining activities, can substancially increase both frequency and severity of a pathogen in a population. Hence, it is important to include both pathogen/parasite presence and pollution load in a waterway when assessing future risk of increased connectivity. **Here we will map pollution load in waterways by combining information of wastewater input in running waters (in relations to its flow) with avaliable monitoring data for key chemicals. To our knowledge this is the first time pollution load and pathogen distribution have been investigated in tandem to identify Water at Risk.**

## Data

No data available yet